<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>0.1.0-preview.0.1.0</PackageValidationBaselineVersion>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.RelationalSchema.RichRelationalModel.EFCore.Models.Configurations</PackageId>
    <RootNamespace>Pure.RelationalSchema.RichRelationalModel.EFCore.Models.Configurations</RootNamespace>
    <AssemblyName>Pure.RelationalSchema.RichRelationalModel.EFCore.Models.Configurations</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.RelationalSchema.RichRelationalModel.EFCore.Models.Configurations</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference
      Include="Pure.Primitives.Abstractions.EFCore.Converters"
      Version="0.1.0-preview.0.1.1"
    />
    <PackageReference
      Include="Pure.Primitives.Abstractions.EFCore.ValueComparers"
      Version="0.1.0-preview.0.1.0"
    />
    <PackageReference
      Include="Pure.RelationalSchema.RichRelationalModel.EFCore.Models"
      Version="0.1.0-preview.0.1.0"
    />
  </ItemGroup>
</Project>
